### ISSUE TITLE
Why do I fail cmake

### ISSUE THREAD

**Issue by nine-city** [Navigine/Indoor-Navigation-Algorithms#17]
The following is cmake error log, I'm new to C + +, can you help me

==========================================
Performing C++ SOURCE FILE Test EIGEN_COMPILER_SUPPORT_CPP11 failed with the following output:
Change Dir: E:/project/C++/navigation/Indoor-Navigation-Algorithms/build/_deps/CMakeFiles/CMakeTmp

Run Build Command(s):E:/vs/MSBuild/Current/Bin/MSBuild.exe cmTC_47b20.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) build engine version 16.8.3 + 39993bd9d for. Net framework

  src.cxx

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D EIGEN_COMPILER_SUPPORT_CPP11 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_47b20.dir\Debug\\" /Fd"cmTC_47b20.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue  -std=c++11 "E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\src.cxx"

cl : PS warning D9002: Ignore unknown options“-std=c++11” [E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\cmTC_47b20.vcxproj]

  cmTC_47b20.vcxproj -> E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\Debug\cmTC_47b20.exe

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test COMPILER_SUPPORT_std=cpp03 failed with the following output:
Change Dir: E:/project/C++/navigation/Indoor-Navigation-Algorithms/build/_deps/CMakeFiles/CMakeTmp

Run Build Command(s):E:/vs/MSBuild/Current/Bin/MSBuild.exe cmTC_b29b1.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) build engine version 16.8.3 + 39993bd9d for. Net framework

  src.cxx

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D COMPILER_SUPPORT_std=cpp03 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_b29b1.dir\Debug\\" /Fd"cmTC_b29b1.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue  -std=c++03 "E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\src.cxx"

cl : PS warning D9002: Ignore unknown options“-std=c++03” [E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\cmTC_b29b1.vcxproj]

  cmTC_b29b1.vcxproj -> E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\Debug\cmTC_b29b1.exe

Source file was:
int main() { return 0; }
Looking for a Fortran compiler failed with the following output:
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_Fortran_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "E:/project/C++/navigation/Indoor-Navigation-Algorithms/build/_deps/_deps/eigen-build/test/CMakeFiles/CheckFortran/CMakeFiles/CMakeOutput.log".
See also "E:/project/C++/navigation/Indoor-Navigation-Algorithms/build/_deps/_deps/eigen-build/test/CMakeFiles/CheckFortran/CMakeFiles/CMakeError.log".

Determining if the include file pthread.h exists failed with the following output:
Change Dir: E:/project/C++/navigation/Indoor-Navigation-Algorithms/build/_deps/CMakeFiles/CMakeTmp

Run Build Command(s):E:/vs/MSBuild/Current/Bin/MSBuild.exe cmTC_95456.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) build engine version 16.8.3 + 39993bd9d for. Net framework

  

  

  CheckIncludeFile.c

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_95456.dir\Debug\\" /Fd"cmTC_95456.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1,10): fatal error C1083: Cannot open include file: “pthread.h”: No such file or directory [E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\cmTC_95456.vcxproj]

Performing C SOURCE FILE Test SCOTCH_Num_4 failed with the following compile output:
Change Dir: E:/project/C++/navigation/Indoor-Navigation-Algorithms/build/_deps/CMakeFiles/CMakeTmp

Run Build Command(s):E:/vs/MSBuild/Current/Bin/MSBuild.exe cmTC_865b0.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) build engine version 16.8.3 + 39993bd9d for. Net framework

  

  

  src.c

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D SCOTCH_Num_4 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_865b0.dir\Debug\\" /Fd"cmTC_865b0.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\src.c"

E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\src.c(4,10): fatal error C1083: Cannot open include file: “scotch.h”: No such file or directory [E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\cmTC_865b0.vcxproj]

...and run output:

Return value: 1
Source file was:

#include <stdio.h>
#include <stdint.h>
#include <scotch.h>
int main(int argc, char **argv) {
  if (sizeof(SCOTCH_Num) == 4)
    return 0;
  else
    return 1;
}

Performing C SOURCE FILE Test SCOTCH_Num_8 failed with the following compile output:
Change Dir: E:/project/C++/navigation/Indoor-Navigation-Algorithms/build/_deps/CMakeFiles/CMakeTmp

Run Build Command(s):E:/vs/MSBuild/Current/Bin/MSBuild.exe cmTC_5c93d.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) build engine version 16.8.3 + 39993bd9d for. Net framework

  

  

  src.c

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D SCOTCH_Num_8 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_5c93d.dir\Debug\\" /Fd"cmTC_5c93d.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\src.c"

E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\src.c(4,10): fatal error C1083: Cannot open include file: “scotch.h”: No such file or directory [E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\cmTC_5c93d.vcxproj]

...and run output:

Return value: 1
Source file was:

#include <stdio.h>
#include <stdint.h>
#include <scotch.h>
int main(int argc, char **argv) {
  if (sizeof(SCOTCH_Num) == 8)
    return 0;
  else
    return 1;
}

Performing C++ SOURCE FILE Test COMPILER_SUPPORT_FASTMATH failed with the following output:
Change Dir: E:/project/C++/navigation/Indoor-Navigation-Algorithms/build/_deps/CMakeFiles/CMakeTmp

Run Build Command(s):E:/vs/MSBuild/Current/Bin/MSBuild.exe cmTC_74faf.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) build engine version 16.8.3 + 39993bd9d for. Net framework

  

  

  src.cxx

  cl /c /Zi /W4 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D _CRT_SECURE_NO_WARNINGS /D _SCL_SECURE_NO_WARNINGS /D COMPILER_SUPPORT_FASTMATH /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_74faf.dir\Debug\\" /Fd"cmTC_74faf.dir\Debug\vc142.pdb" /Gd /TP /wd4127 /wd4505 /wd4714 /errorReport:queue  -ffast-math "E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\src.cxx"

cl : PS warning D9002: Ignore unknown options“-ffast-math” [E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\cmTC_74faf.vcxproj]

  cmTC_74faf.vcxproj -> E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\Debug\cmTC_74faf.exe

Source file was:
int main() { return 0; }
Performing C++ SOURCE FILE Test COMPILER_SUPPORT_std=cpp03 failed with the following output:
Change Dir: E:/project/C++/navigation/Indoor-Navigation-Algorithms/build/_deps/CMakeFiles/CMakeTmp

Run Build Command(s):E:/vs/MSBuild/Current/Bin/MSBuild.exe cmTC_4c128.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) build engine version 16.8.3 + 39993bd9d for. Net framework

  

  

  src.cxx

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D COMPILER_SUPPORT_std=cpp03 /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_4c128.dir\Debug\\" /Fd"cmTC_4c128.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue  -std=c++03 "E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\src.cxx"

cl : PS warning D9002: Ignore unknown options“-std=c++03” [E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\cmTC_4c128.vcxproj]

  cmTC_4c128.vcxproj -> E:\project\C++\navigation\Indoor-Navigation-Algorithms\build\_deps\CMakeFiles\CMakeTmp\Debug\cmTC_4c128.exe

Source file was:
int main() { return 0; }

**Comment by GVolosnyh** [comment]
Hi, unfortunately we cannot reproduce your problem because we do not use Windows and do not provide support. However, you can try the recommendations from [here](https://github.com/Microsoft/vcpkg/issues/3801).

**Comment by nine-city** [comment]
thanks
