### ISSUE TITLE
Question about Particle Filter

### ISSUE THREAD

**Issue by msdrigg** [Navigine/Indoor-Navigation-Algorithms#20]
Hey Navigine Team,

I saw your video on particle filters on your Youtube channel, and I found this repository that contains some code that seems to apply to that concept. But the code doesn't seem to have a complete example or algorithm. Is there any chance you could point it out to me or add it to the repository if it is missing?

Thank you so much for creating a great open source repository

**Comment by GVolosnyh** [comment]
Hi, @msdrigg 

Unfortunately, the **particle filter** is our main internal development, and we do not plan to publish it in the near future. To implement your own algorithm, you can search for scientific articles on the topic: complexing inertial data and radio measurements for indoor navigation, or use other algorithms that are in our repository.

**Comment by msdrigg** [comment]
Thanks Gvolosnyh,

I totally understand the reason. Thanks for the work you are sharing with the world and good luck with your product.

Scott
