### ISSUE TITLE
Navigine Licence Agreement

### ISSUE THREAD

**Issue by bleckers** [Navigine/Indoor-navigation-algorithms#4]
Hi Alex,

I am just wondering what software licence agreement you are distributing the Navigine software under, I cannot seem to find it anywhere (the docs site just has a licence for the documentation itself).

I would like to incorporate this into an open source project (with full recognition back to this project), but just want to make sure the licence is compatible before proceeding.

Regards,

Blair

**Comment by AlexeyPanyov** [comment]
Re: [Indoor-navigation-algorithms] Navigine Licence Agreement (#4)



Hi Blair,

Thnx for the question,
we are happy to help you with your project.

Let's shortly discuss it via Skype.

Best regards,
Alexey Panyov
PhD, CEO of Navigine,
www.navigine.com
skype: alexey.panev
phone: +79266599850





Hi Alex,
I am just wondering what software licence agreement you are distributing the Navigine under, I cannot seem to find it anywhere (the docs site just has a licence for the documentation itself).
I would like to incorporate this into an open source project (with full recognition back to this project), but just want to make sure the licence is compatible before proceeding.
Regards,
Blair
